server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

springboot.main-run-controller : true
persistence:
  #QA
  user: root
  password: password
  databaseName: EmployeeDB
  serverName: user
  portNumber: 3306
  maximumPoolSize: 10
  idleConnectionTimeout: 60000
  minimumIdleConnection: 30
  maxLifeTime: 21600000
  connectionTimeout: 500000
  jdbcUrl: "jdbc:mysql://localhost:3306/user?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&useUnicode=yes&characterEncoding=UTF-8"
logging.level.org.springframework.web: INFO
hibernate.show_sql: false